# LINEAR ALGEBRA

### Vectors 

In linear algebra, a vector is an array of numbers arranged in a specific order. Vectors can represent points in space, directions, or any quantity defined by magnitude and direction


In [1]:
import numpy as np 

# Define a vector 
vector = np.array([2, 3, 5])
print(f"Vector: {vector}")

# Access elements 
first_element = vector[0]
print(f"First element: {first_element}")

# Vector Operatations
vector_length = np.linalg.norm(vector)
print(f"Magnitude of the vector: {vector_length}")

Vector: [2 3 5]
First element: 2
Magnitude of the vector: 6.164414002968976


### Matrices

A matrix is a two-dimensional array of numbers arranged in rows and columns. Matrices are used to represent linear transformation and systems of linear equations.

In [2]:
# Define a matrix
matrix = np.array([
    [4,2,5],
    [8,6,5],
    [6,9,8]])
print(f"MATRIX: {matrix}")

# Access elements
element = matrix[1, 2]
print(f"Element of the matrix {element}")

# Matrix operations
transpose = matrix.T
print(f"Transpose of the matrix {transpose}")

determinant = np.linalg.det(matrix)
print(f"Determinant of the matrix: {determinant}")

MATRIX: [[4 2 5]
 [8 6 5]
 [6 9 8]]
Element of the matrix 5
Transpose of the matrix [[4 8 6]
 [2 6 9]
 [5 5 8]]
Determinant of the matrix: 123.99999999999991


### EigenValues and EigenVectors

For a square a matrix A, an eigenvector is a non-zero vector v such that when A is multiplied by v, the result is a scalar of v. The scalar is know as the eigenvalue corresponding to that eigenvector.

In [4]:
A = np.array([[4,2],[1,3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors: {eigenvectors}")

Eigenvalues: [5. 2.]
Eigenvectors: [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


### Single Value Descomposition (SVD)


SVD decomposes a matrix \( A \) into three matrices: \( U \), \( \Sigma \), and \( V^T \), such that \( A = U \Sigma V^T \). This decomposition is useful in various applications, including dimensionality reduction and noise reduction.

In [5]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Perform SVD 
U, S, VT = np.linalg.svd(A)

print(f"U matrix: \n{U}")
print(f"Singular Values: {S}")
print(f"V^T matrix\n:{VT}")

U matrix: 
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular Values: [9.52551809 0.51430058]
V^T matrix
:[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


### 5 Linear Transformations 

A linear transformation is a mapping between vector spaces that preserves vector addition and scalar multiplication. Matrices can represent linear transformations.

In [7]:
# Define a matrix representing a linear transformation
transformation_matrix = np.array([[2, 0], [0, 3]])

# Define a vector
vector = np.array([1, 1])

# Apply the linear transformation
transformed_vector = np.dot(transformation_matrix, vector)

print(f"Transformed vector: {transformed_vector}")

Transformed vector: [2 3]


### Vector Space and Subspace

A vector space is a collection of vector that can be added together and multiplied by scalar to produce another vector in the same space. A subspace is a subset of a vector space that is also a vector space under the same operations.

In [9]:
# Define two vectors in R^3
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])

# Check if their linear combination is the same space
linear_combination = 3 * v1 + 4 * v2

print(f"Linear combination : {linear_combination}")


Linear combination : [3 4 0]
